

GET http://localhost:3001/api/users

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "benjamin2.0",
    "email": "benjamin2.0@gmail.com",
    "password": "benjamin2.0"
}

###

POST http://localhost:3001/api/users/login
Content-Type: application/json

{
    "email": "benjamin2.0@gmail.com",
    "password": "benjamin2.0"
}